//! `SeaORM` Entity, generated by spring-boot-rest-generator (rust-loco target).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "invoices")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub invoice_id: i32,
    pub customer_id: i32,
    pub invoice_date: DateTimeWithTimeZone,
    pub billing_address: String,
    pub billing_city: String,
    pub billing_state: String,
    pub billing_country: String,
    pub billing_postal_code: String,
    pub total: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
