//! `SeaORM` Entity, generated by spring-boot-rest-generator (rust-loco target).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tracks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub track_id: i32,
    pub name: String,
    pub album_id: i32,
    pub media_type_id: i32,
    pub genre_id: i32,
    pub composer: String,
    pub milliseconds: i32,
    pub bytes: i32,
    pub unit_price: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
