//! `SeaORM` Entity, generated by spring-boot-rest-generator (rust-loco target).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "employee_territories")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub employee_id: i32,
    pub territory_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
