//! `SeaORM` Entity, generated by spring-boot-rest-generator (rust-loco target).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "orders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub order_id: i32,
    pub customer_id: String,
    pub employee_id: i32,
    pub order_date: DateTimeWithTimeZone,
    pub required_date: DateTimeWithTimeZone,
    pub shipped_date: DateTimeWithTimeZone,
    pub ship_via: i32,
    pub freight: f64,
    pub ship_name: String,
    pub ship_address: String,
    pub ship_city: String,
    pub ship_region: String,
    pub ship_postal_code: String,
    pub ship_country: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
