//! `SeaORM` Entity, generated by spring-boot-rest-generator (rust-loco target).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "products")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub product_id: i32,
    pub product_name: String,
    pub supplier_id: i32,
    pub category_id: i32,
    pub quantity_per_unit: String,
    pub unit_price: f64,
    pub units_in_stock: i16,
    pub units_on_order: i16,
    pub reorder_level: i16,
    pub discontinued: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
