//! `SeaORM` Entity, generated by spring-boot-rest-generator (rust-loco target).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "rentals")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub rental_id: i32,
    pub rental_date: DateTimeWithTimeZone,
    pub inventory_id: i32,
    pub customer_id: i32,
    pub return_date: DateTimeWithTimeZone,
    pub staff_id: i32,
    pub last_update: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
